In [1]:
import numpy as np
from sympy import *

Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

Определитель $detA$ второго порядка,  матрицы $A$ определяется как

$$detA=|A|=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

$$detA = |A| = \left| {\begin{array}{*{20}{c}}
{sinx}&{ - cosx}\\
{cosx}&{sinx}
\end{array}} \right| = sinx \cdot sinx + cosx \cdot cosx = sin{x^2} + cos{x^2} = 1.$$

In [2]:
x = symbols("x")
M = Matrix([[sin(x), -cos(x)], [cos(x), sin(x)]])
a = M.det()

print(f'Матрица:\n{M}')
print(f'Определитель:\n{a}')
print(f'Определитель:\n{simplify(a)}')


Матрица:
Matrix([[sin(x), -cos(x)], [cos(x), sin(x)]])
Определитель:
sin(x)**2 + cos(x)**2
Определитель:
1


Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) Согласно свойству матриц, для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB.$ Следовательно 
$$det(A^2)=det(AA)\;=\;det(A)det(A)=4\times4=16$$

б) Согласно свойству матриц, определитель транспонированной матрицы равен определителю исходной. Откуда $det(A^{T})=4$

в) Согласно свойству матриц, умножение строки или столбца матрицы на число  𝜆  приведет к умножению определителя матрицы на то же число. Следовательно 
$$det(2A)=2\times4=8$$

Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

По определеию, матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

Вычислим определитель заданной матрицы.

$\begin{pmatrix}-2&7&-3\\4&-14&6\\-3&7&13\end{pmatrix}=-2\begin{vmatrix}-14&6\\7&13\end{vmatrix}-7\begin{vmatrix}4&6\\-3&13\end{vmatrix}-3\begin{vmatrix}4&-14\\-3&7\end{vmatrix}=-2\cdot(-14\cdot13-7\cdot6)-7\cdot(4\cdot13+3\cdot6)-3\cdot(4\cdot7-14\cdot3)=448-490+42=0$

Матрица является вырожденной.

In [3]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) найдем минор второго порядка 

$\left| {\begin{array}{*{20}{c}}
1&2\\
1&1
\end{array}} \right| = 1 - 2 =  - 1$ так как минор не равен 0, то ранг матрицы $r \ge 2$

Найдем минор 3го порядка который совпадает с определителем матрицы.

$\left( {\begin{array}{*{20}{c}}
1&2&3\\
1&1&1\\
2&3&4
\end{array}} \right) = \left| {\begin{array}{*{20}{c}}
1&1\\
3&4
\end{array}} \right| - \left| {\begin{array}{*{20}{c}}
1&1\\
2&4
\end{array}} \right| + \left| {\begin{array}{*{20}{c}}
1&1\\
2&3
\end{array}} \right| = 4 - 3 - 4 + 2 + 3 - 2 = 0$

Так как минор 3го порядка равен 0, то ранг матрицы $r \ge 2$

а) найдем минор второго порядка

$\left| {\begin{array}{*{20}{c}}
2&1\\
2&2
\end{array}} \right| = 4 - 2 = 2$ так как минор не равен 0, то ранг матрицы $r \ge 2$

Найдем минор 3го порядка

$\left| {\begin{array}{*{20}{c}}
0&2&2\\
0&4&3\\
3&5&6
\end{array}} \right| = 0 - 2 \cdot \left| {\begin{array}{*{20}{c}}
0&3\\
3&6
\end{array}} \right| + 2 \cdot \left| {\begin{array}{*{20}{c}}
0&4\\
3&5
\end{array}} \right| = 18 - 24 =  - 6$ так как минор не равен 0, то ранг матрицы $r \ge 3$

Найдем минор 4го порядка который совпадает с определителем матрицы.

$\left( {\begin{array}{*{20}{c}}
0&0&2&1\\
0&0&2&2\\
0&0&4&3\\
2&3&5&6
\end{array}} \right) = 0 - 0 + 2 \cdot \left| {\begin{array}{*{20}{c}}
0&0&2\\
0&0&3\\
2&3&6
\end{array}} \right| - \left| {\begin{array}{*{20}{c}}
0&0&2\\
0&0&4\\
2&3&5
\end{array}} \right| = 2 \cdot \left( {0 - 0 + 2 \cdot \left| {\begin{array}{*{20}{c}}
0&0\\
2&3
\end{array}} \right|} \right) + \left( {0 - 0 + 2 \cdot \left| {\begin{array}{*{20}{c}}
0&0\\
2&3
\end{array}} \right|} \right) = 0$ 

Так как минор 4го порядка равен 0, то ранг матрицы $r \ge 3$


In [4]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)
print(f'Ранг матрицы a: {r}')

b = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
r = np.linalg.matrix_rank(b)
print(f'Ранг матрицы б: {r}')


Ранг матрицы a: 2
Ранг матрицы б: 3


Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   

что бы матрицу $A$ можно было умножить матрицу $B$, __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

_Произведением_ матрицы $A = \left\|a_{ij}\right\|$, имеющей порядки $m$ и $n$, и матрицы $B = \left\|b_{ij}\right\|$, имеющей порядки $n$ и $k$, называется матрица $C = \left\|c_{ij}\right\|$, имеющая порядки $m$ и $k$.

Из этого следует, что:

а) произведение матриц $AB$ и $BA$ не определены, так как число столбцов и строк матриц не равны

б) произведение матриц $AB$, размерность матрицы $2 \times 3$

в) произведение матриц $AB$ и $BA$ определены, размерность $8 \times 8$ и $3 \times 3$ соответственно.

г) произведение матриц $AB$ и $BA$ определены, размерность $4 \times 4$ для обоих произведений.


Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Сумма матриц

$A + B = \left( {\begin{array}{*{20}{c}}
1&{ - 2}\\
3&0
\end{array}} \right) + \left( {\begin{array}{*{20}{c}}
4&{ - 1}\\
0&5
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{1 + 4}&{ - 2 - 1}\\
{3 + 0}&{0 + 5}
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
5&{ - 3}\\
3&5
\end{array}} \right)$


Произведенрие матриц

$A \cdot B = \left( {\begin{array}{*{20}{c}}
1&{ - 2}\\
3&0
\end{array}} \right) \cdot \left( {\begin{array}{*{20}{c}}
4&{ - 1}\\
0&5
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{1 \cdot 4 - 2 \cdot 0}&{ - 1 - 2 \cdot 5}\\
{3 \cdot 4 + 0 \cdot 0}&{ - 1 \cdot 3 + 0 \cdot 5}
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
4&{ - 11}\\
{12}&{ - 3}
\end{array}} \right)$



Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


$3 \cdot \left( {\begin{array}{*{20}{c}}
1&7\\
3&{ - 6}
\end{array}} \right) - 2 \cdot \left( {\begin{array}{*{20}{c}}
0&5\\
2&{ - 1}
\end{array}} \right) + 4 \cdot \left( {\begin{array}{*{20}{c}}
2&{ - 4}\\
1&1
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
3&{21}\\
9&{ - 18}
\end{array}} \right) - \left( {\begin{array}{*{20}{c}}
0&{10}\\
4&{ - 2}
\end{array}} \right) + \left( {\begin{array}{*{20}{c}}
8&{ - 16}\\
4&4
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{3 - 0 + 8}&{21 - 10 - 16}\\
{9 - 4 + 4}&{ - 18 + 2 + 4}
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{11}&{ - 5}\\
9&{ - 12}
\end{array}} \right)$
 

Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

${A^T} = \left( {\begin{array}{*{20}{c}}
4&5&2\\
1&{ - 2}&3
\end{array}} \right)$

${A^T} \cdot A = \left( {\begin{array}{*{20}{c}}
4&5&2\\
1&{ - 2}&3
\end{array}} \right) \cdot \left( {\begin{array}{*{20}{c}}
4&1\\
5&{ - 2}\\
2&3
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2}&{4 \cdot 1 - 2 \cdot 5 + 3 \cdot 2}\\
{1 \cdot 4 - 2 \cdot 5 + 3 \cdot 2}&{1 \cdot 1 + 2 \cdot 2 + 3 \cdot 3}
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{45}&0\\
0&{14}
\end{array}} \right)$

$A \cdot {A^T} = \left( {\begin{array}{*{20}{c}}
4&1\\
5&{ - 2}\\
2&3
\end{array}} \right) \cdot \left( {\begin{array}{*{20}{c}}
4&5&2\\
1&{ - 2}&3
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{4 \cdot 4 + 1 \cdot 1}&{4 \cdot 5 - 2 \cdot 1}&{4 \cdot 2 + 1 \cdot 3}\\
{5 \cdot 4 - 2 \cdot 1}&{5 \cdot 5 + 2 \cdot 2}&{2 \cdot 5 - 2 \cdot 3}\\
{2 \cdot 4 + 3 \cdot 1}&{2 \cdot 5 - 2 \cdot 3}&{2 \cdot 2 + 3 \cdot 3}
\end{array}} \right) = \left( {\begin{array}{*{20}{c}}
{17}&{18}&{11}\\
{18}&{29}&4\\
{11}&4&{13}
\end{array}} \right)$

In [5]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
At

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [6]:
print(f'Матрица AB\n{np.dot(A, At)}')

Матрица AB
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [7]:
print(f'Матрица AB\n{np.dot(At, A)}')

Матрица AB
[[45  0]
 [ 0 14]]
